#!/bin/bash
#PBS -q auto_free
#PBS -o logs/lhs_samples_snr32_v2.out
#PBS -e logs/lhs_samples_snr32_v2.err
#PBS -N lhs_v2
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb

cd $PBS_O_WORKDIR;

mkdir -p logs

source /scratch/e1498138/anaconda3/bin/activate fewsm

export CUDA_VISIBLE_DEVICES=0

python -u run_lhs_snr32.py --n-samples 500000 --seed 123 --outdir ./lhs_snr32_checkpoints_v2

echo "Job completed at $(date)"
