#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/paper/ext_emri_g/stage1_merge_s12_dev.out
#PBS -e logs/paper/ext_emri_g/stage1_merge_s12_dev.err
#PBS -N paris1
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

echo "Job ID: $PBS_JOBID"
echo "Job name: $PBS_JOBNAME"
echo "Job starts at $(date)"

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u paris1_sc_ext_dev.py

echo "Job completed at $(date)"
