#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/lhs_noise_detsnr_new.out
#PBS -e logs/lhs_noise_detsnr_new.err
#PBS -N lhs_detsnr
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u run_lhs_noise_detsnr.py --n-samples 100000 --batch-size 10 --outdir /scratch/e1498138/lhs/noise/detsnr/ckpt_1e5_new

echo "Job completed at $(date)"
