#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/paper/ext_emri_g/paris3_lhs_s6_dev.out
#PBS -e logs/paper/ext_emri_g/paris3_lhs_s6_dev.err
#PBS -N paris3_lhs_s6_dev
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u paris3_lhs_s6_ext.py

echo "Job completed at $(date)"
