#!/bin/bash
#PBS -q auto_free
#PBS -o logs/precompute_lhs_paris3_1yr.out
#PBS -e logs/precompute_lhs_paris3_1yr.err
#PBS -N lhs_pre
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb

cd $PBS_O_WORKDIR;

mkdir -p logs

source /scratch/e1498138/anaconda3/bin/activate fewsm

export CUDA_VISIBLE_DEVICES=0

python -u precompute_lhs_paris3.py

echo "Job completed at $(date)"
