#!/bin/bash
#PBS -q auto_free
#PBS -o logs/intrinsic_ffunc_3mth_snr32_opt_pure.out
#PBS -e logs/intrinsic_ffunc_3mth_snr32_opt_pure.err
#PBS -N opt_pure
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb

cd $PBS_O_WORKDIR;

mkdir -p logs

source /scratch/e1498138/anaconda3/bin/activate fewsm

export CUDA_VISIBLE_DEVICES=0

python -u intrinsic_ffunc_3mth_faceon_opt_pure.py

echo "Job completed at $(date)"
