#!/bin/bash
#PBS -q auto_free
#PBS -N greedy_opt
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb
#PBS -o logs/greedy_pure_opt_paris.out
#PBS -e logs/greedy_pure_opt_paris.err

cd $PBS_O_WORKDIR;
mkdir -p logs

source /scratch/e1498138/anaconda3/bin/activate fewsm

export CUDA_VISIBLE_DEVICES=0

python -u greedy_pure_opt.py

echo "Job completed at $(date)"
