#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/paper/lhs_stage3_ellipsoid.out
#PBS -e logs/paper/lhs_stage3_ellipsoid.err
#PBS -N lhs_stage3_ellipsoid
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

mkdir -p logs/paper
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u paris5_lhs_ext_stage2_ellipsoid.py

echo "Job completed at $(date)"
