#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/sobol_noise_tpmax.out
#PBS -e logs/sobol_noise_tpmax.err
#PBS -N sobol_noise_tpmax
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u run_sobol_noise.py --n-samples 100000 --batch-size 10 --outdir /scratch/e1498138/sobol/noise/tpmax/ckpt_1e5

echo "Job completed at $(date)"
