#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/paper/ext_emri_g/lhs_f.out
#PBS -e logs/paper/ext_emri_g/lhs_f.err
#PBS -N paper_lhs_f
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u run_lhs_noise_ext.py --n-samples 100000 --batch-size 10 --outdir /scratch/e1498138/paper/ext/emri_g/lhs_f/

echo "Job completed at $(date)"
