#!/bin/bash
#PBS -q auto_free
#PBS -o logs/intrinsic_ffunc_3mth_snr32_paris3_4.out
#PBS -e logs/intrinsic_ffunc_3mth_snr32_paris3_4.err
#PBS -N paris3_3
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb

cd $PBS_O_WORKDIR;

mkdir -p logs

source /scratch/e1498138/anaconda3/bin/activate fewsm

export CUDA_VISIBLE_DEVICES=0

python -u intrinsic_ffunc_3mth_faceon_paris3.py

echo "Job completed at $(date)"
