#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/mode_power_distribution.out
#PBS -e logs/mode_power_distribution.err
#PBS -N mode_power_dist
#PBS -l walltime=02:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR

echo "Job ID: $PBS_JOBID"
echo "Job name: $PBS_JOBNAME"
echo "Job starts at $(date)"

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python mode_power_distribution.py

echo "Job completed at $(date)"
