#!/bin/bash
#PBS -P CFP03-CF-051
#PBS -o logs/box1_15sig_lhs_ellipsoid_5e5.out
#PBS -e logs/box1_15sig_lhs_ellipsoid_5e5.err
#PBS -N box1_15sig_lhs_ellipsoid
#PBS -l walltime=24:00:00
#PBS -l select=1:ngpus=1

cd $PBS_O_WORKDIR;

echo "Job ID: $PBS_JOBID"
echo "Job name: $PBS_JOBNAME"
echo "Job starts at $(date)"

mkdir -p logs
module load cuda12.4/toolkit/12.4.1
source /home/svu/e1498138/emri_search_uv/.venv/bin/activate

python -u box1_lhs_ellipsoid.py --n-sigma 15

echo "Job completed at $(date)"
